package com.ntsi.messageprocessor.model.db;

public enum MetricType {
    TRACKER_DATA_GPS_LOCATION_LAT_LNG,

    TRACKER_DATA_GPS_ELEVATION,

    TRACKER_DATA_GPS_SPEED,

    TRACKER_DATA_GPX_TIME,

    TRACKER_DATA_GPS_NAME,

    TRACKER_DATA_GPS_COMMENT,

    TRACKER_DATA_GPS_DESCRIPTION,

    TRACKER_DATA_GPS_TYPE,

    TRACKER_DATA_GPS_SOURCE,

    TRACKER_DATA_GPS_SYMBOL,


}